name: unknown-finder

channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.11
  - pip
  - numpy
  - pandas
  - scipy
  - scikit-learn
  - matplotlib
  - seaborn
  - tqdm
  - pyyaml
  - requests
  - python-dotenv
  - pydantic
  - pytest
  - pip:
      - pytest-cov
      - httpx
      - respx